modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="vanillastyleautocrafting"
version="1.0.0"
displayName="VanillaStyleAutoCrafting"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Mosselini1, MCreator"
description='''
an auto-crafting implementation vanilla style
'''

[[dependencies.vanillastyleautocrafting]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




